import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>y&apos;s room</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="text-4xl">自己紹介</header>
      <main>メイン</main>
      <footer>@yuki-TU</footer>
    </div>
  );
};

export default Home;
